### ISSUE TITLE
Error Too Many Requests

### ISSUE THREAD

**Issue by adrianosantostreina** [AliDehbansiahkarbon/ChatGPTWizard#51]
Hi,
I'm receiving an error bellow when I try to ask for ChatGPT plugin on Delphi 11.3.
HTTP/1.1 429 Too Many Requests

I'm used the dll files onto /resources

Thanks

**Comment by adrianosantostreina** [comment]
Hi,

I didn't really ask many questions.  A single attempt is enough to trigger
this error.  It's been a few days since I installed the plug-in and I
couldn't succeed in any attempt.  But I will read the articles you
suggested.  Thanks

Em seg., 19 de jun. de 2023 17:30, Ali Dehbansiahkarbon <
***@***.***> escreveu:

**Comment by AliDehbansiahkarbon** [comment]
Did you read those articles? (I bet not)
"Too many requests", is the exact response of the API.
It means the plug-in sends the request and gets the response successfully, nothing to do with the plug-in, this is about the API rates.

You can try **Postman** or **Rest Debugger** to make sure.
In the meantime, the website may work because the API rates limit is different from the website rates limit.

I had the same issue with my free account, the only way is to use a paid account or make another user, and you'll see it works again.

A temporary way could be using a VPN which is able to change your IP address to US or UK, maybe it works for a while but not permanently.

**Comment by adrianosantostreina** [comment]
You bet wrong friend, sorry. And it seems to me that you are not very used to chatting with people, maybe ChatGPT will be your salvation.

Yes, I read it and I know very well what "Too many requests" means. My OpenAI account is free and new, I haven't executed any requests, neither through Postman, nor RESTDebuger, much less through your plugin. But that's ok, I'll follow your final tips and see if it works, otherwise I'll make my own Expert, I just don't want to reinvent the wheel since there is yours and I can also share it with my followers and students. Anyway.

Thank you very much. Success to you.

**Comment by AliDehbansiahkarbon** [comment]
So, I'm wondering why you are asking again with a video while you read those articles.
Anyway, it was a bet, I can easily lose!

Just keep in mind I have to answer the same question a hundred times per day, I expect experts to know about the API behavior, this plug-in is simply a client app, it cannot produce that error message at all.

Wish you the best of luck.

**Comment by adrianosantostreina** [comment]
Relax

Em qua., 21 de jun. de 2023 08:48, Ali Dehbansiahkarbon <
***@***.***> escreveu:
