### ISSUE TITLE
Offline(ollama) choice missing.

### ISSUE THREAD

**Issue by andreaskslette** [AliDehbansiahkarbon/ChatGPTWizard#59]
Just installed version 2.2.0.9 from getIt, but the Offline(ollama) choice is not in the settings.

**Comment by AliDehbansiahkarbon** [comment]
It's not in the setting (Check box), as I wrote in the ReadMe ([here](https://github.com/AliDehbansiahkarbon/ChatGPTWizard#:~:text=How%20to%20use%20it%20in%20Offline%20mode)) you must tick the offline checkbox and type the model name in a separate new text box, because there are 100 offline models and I don't know which one is better now.

![image](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/5601608/ca04a05a-866d-4211-a35f-76fd976a817d)

**Comment by andreaskslette** [comment]
Where do i find the offline checkbox?
![image](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/166121423/0002b423-eb16-4ac9-a281-54fa2caf141b)

I can see that there is a TChecbox called chk_Offline in UChatGPDTSetting.dfm, but i don't have it in my screenshot.

**Comment by AliDehbansiahkarbon** [comment]
I sent the request to Embarcadero but the Getit version is not updated yet.
So please Uninstall that version and try the latest version from GitHub. (make a clone or download zip)

![image](https://github.com/AliDehbansiahkarbon/ChatGPTWizard/assets/5601608/601bb23b-cfbc-4615-a63b-645467c78061)

**Comment by andreaskslette** [comment]
Okay, will give that a try, thanks!
